#ifndef OBJECTTYPE_H_INCLUDED
#define OBJECTTYPE_H_INCLUDED

namespace MyPattern
{
    namespace Base
    {
        enum ObjectType { OBJECTTYPE_UNKNOWN, OBJECTTYPE_LANDMARK, OBJECTTYPE_CURVE, OBJECTTYPE_MEASURE, OBJECTTYPE_PARAMETER };
    }
}


#endif // OBJECTTYPE_H_INCLUDED
