#ifndef PATTERNTYPE_H_INCLUDED
#define PATTERNTYPE_H_INCLUDED

enum PatternType {PATTERNTYPE_MALE, PATTERNTYPE_FEMALE, PATTERNTYPE_UNISEX, PATTERNTYPE_BOYS, PATTERNTYPE_GIRLS, PATTERNTYPE_ACCESSOIRE};

#endif // PATTERNTYPE_H_INCLUDED
